### ISSUE TITLE
Página para mostrar el Folleto del curso

### ISSUE THREAD

**Issue by proefra27** [dbetm/SRACP#15]
Tenemos dos páginas:

1.- En el admin donde subimos la imagen.
2.- En el Front-end donde se muestra a los aspirantes y al darle click redirecciona al registro
3.- Incluimos aquí el chat para todas las dudas que puedan surgir

[Link de Ejemplo](http://www.zacatecas.ipn.mx/Documents/preregistro.html)

**Comment by dbetm** [comment]
1) Se generó la vista para el admin, un apartado para subir la nueva imagen del folleto y actualizar, y el otro para visualizar la actual; también es posible ir a la [vista del folleto](http://movilesupiiz.site/movilesupiiz.site/betancourtd/SRACP/promo.html) para los aspirantes dando click en "Folleto actual".
2) Se hizo la vista para los aspirantes, desde donde pueden dar click e ir a la [vista del registro](http://movilesupiiz.site/movilesupiiz.site/betancourtd/SRACP/index.html).
3* Falta el chat.
Commit: cc0f76205c2a18bf1e56b44b9dd5449b61aae7a6
