### ISSUE TITLE
Instructivo: Al finalizar el registro

### ISSUE THREAD

**Issue by proefra27** [dbetm/SRACP#23]
Una vez que se manda el mensaje de registro exitoso, debe de mostrar el siguiente instructivo:

![imgen_pago_3](https://user-images.githubusercontent.com/10124002/42531666-2bec47f6-844a-11e8-92a9-6c46168bbc8a.png)

Así también debe de enviarle a su correo este procedimiento.

Con esto es necesario agregar una opción al admin donde pueda escribir este instructivo.

Usaremos el plugin de [Tiny](https://www.tiny.cloud/)

**Comment by proefra27** [comment]
También mandarle un correo al administrador de que existe un nuevo registro.

**Comment by dbetm** [comment]
++ Se generó la vista en [Nombre admin logueado] > Instructivo.
ADMIN
+ Se trabajó con Tiny como editor de texto.
+ Al darle en guardar se muestra un alert para confirmar la actualización.
+ Las imágenes se insertan por medio de una URL.
+ Desde el título **Actualizar [instructivo](http://movilesupiiz.site/movilesupiiz.site/betancourtd/SRACP/instructivo.php)** es posible ir a la vista que ven los aspirantes.

+ El aspirante se le redirecciona al [Instructivo](http://movilesupiiz.site/movilesupiiz.site/betancourtd/SRACP/instructivo.php) cuando se ha registrado correctamente.
+ En la parte superior justo después de donde dice **Instructivo** se muestra una banda para notificar al aspirante de que se ha registrado correctamente.
+ En el footer se muestran algunos iconos de redes sociales.

![captura de pantalla de 2018-07-29 14-45-45](https://user-images.githubusercontent.com/14257441/43370078-2017ff1c-933e-11e8-9191-ff96ad97083e.png)

**Comment by dbetm** [comment]
+ Se quitó el título **Instructivo** de la vista para el aspirante.
+ Se hace más grande la banda superior de "Se ha registrado exitosamente".
Commit: 4cbe4d4b7aa11d625537a9a9ca1e095d551d6da7
